import { ReactNode } from "react";

// types.ts
export interface Translations {
  English:string;
  Arabic:string;
    SubscriptionError: string;
    selectService: ReactNode;
    home: string;
    about: string;
    contact: string;
    services: string;
    doctors: string;
    blogs: string;
    bookNow: string;
    loading: string; 
    slideTitle:string;
    slideText:string;
    AboutSectionHeader:string;
    OurOffers:string;
    loadingOffers:string;
    SeeOurOffersLink:string;
    OurServices:string;
    SeeOurServices:string;
    CounterTitle:string;
    Specialists:string;
    Departments:string;
    Yearsofexperience:string;
    Patientseveryday:string;
    MeetOurSpecialists:string;
    SeeOurDoctors:string;
    OurTeam:string;
    noServicesAvailable:string;
    servicesName:string;
    servicePageTitle:string;
    FooterTitle:string;
    StayUptodate:string;
    Tel:string;
    SubscribeNow:string;
    SubscriptionSuccess:string;
    OfferPageText:string;
    DoctorPageText:string;
    FormName:string;
    FormEmail:string;
    FormPhone:string;
    FormMessage:string;
    FormService:string;
    Submit:string;
    Open:string;
    PearlSmile:string;
    MedicalCenter:string;
    Address:string;
    groundPhone:string;
    readMore:string;
    mediaGallery:string;
    photos:string;
    videos:string;
    loadingVideo:string;
    aboutTitleSeo:string;
    aboutKeySeo:string;
    aboutDesSEo:string;
    blogTitleSeo:string;
    blogKeySeo:string;
    blogDesSeo:string;
    PearlSmileSeo:string;
    DoctorProfileDesSeo:string;
    Noimageavailable:string;
    loadingBlog:string;
    noFaqAvailable:string;
    faq_head:string;
    service_offer_head:string;
    service_doctor_head:string;
    HomeDesc:string;
    HomeKeys:string;
    AboutDesc:string;
    AboutKeys:string;
    serviceDesc:string;
    serviceKeys:string;
    DoctorDesc:string;
    DoctorKeys:string;
    offerDes:string;
    offerKeys:string;
    GalleryTitle:string;
    GalleryDesc:string;
    GalleryKeys:string;
    ContactTitle:string;
    loadingDoctors:string;
  }

  